name: pyspark_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - openjdk=17      # nécessaire pour Spark
  - pip:
      - pyspark==4.0.0
      - pytest         # si tu veux les tests
